/**
 * Dashboard.jsx — Guardian View
 * Warm, approachable design. No cold clinical tables.
 */

import { useState, useEffect, useRef } from "react";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:5001";

function Sparkline({ data = [], color = "#9b5e38", h = 40 }) {
  if (!data || data.length < 2) return <div style={{ height: h }} />;
  const w = 120;
  const mn = Math.min(...data), mx = Math.max(...data);
  const rng = mx - mn || 1;
  const pts = data.map((v, i) => [
    (i / (data.length - 1)) * w,
    h - ((v - mn) / rng) * (h - 6) - 3,
  ]);
  const d = pts.map((p, i) => `${i === 0 ? "M" : "L"}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" ");
  return (
    <svg width={w} height={h} style={{ display: "block" }}>
      <path d={d} fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function ScoreChart({ scores = [], accentColor, border, muted }) {
  const canvasRef = useRef(null);
  const chartRef = useRef(null);
  useEffect(() => {
    if (!scores.length) return;
    const load = async () => {
      if (!window.Chart) {
        await new Promise((res, rej) => {
          const s = document.createElement("script");
          s.src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js";
          s.onload = res; s.onerror = rej;
          document.head.appendChild(s);
        });
      }
      if (chartRef.current) chartRef.current.destroy();
      const labels = scores.map((_, i) => `${i * 3}s`);
      const data = scores.map(s => s.asdScore ?? s);
      chartRef.current = new window.Chart(canvasRef.current, {
        type: "line",
        data: {
          labels,
          datasets: [{
            data, borderColor: accentColor,
            backgroundColor: accentColor + "18",
            borderWidth: 2.5,
            pointRadius: data.length > 30 ? 0 : 3,
            pointBackgroundColor: accentColor,
            tension: 0.45, fill: true,
          }],
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          plugins: { legend: { display: false } },
          scales: {
            y: { min: 0, max: 100, grid: { color: border + "66" }, ticks: { font: { family: "Nunito", size: 11 }, color: muted } },
            x: { grid: { display: false }, ticks: { font: { family: "Nunito", size: 10 }, color: muted, maxTicksLimit: 8, maxRotation: 0 } },
          },
        },
      });
    };
    load();
    return () => chartRef.current?.destroy();
  }, [scores, accentColor]);
  return <div style={{ height: 200, position: "relative" }}><canvas ref={canvasRef} /></div>;
}

async function exportPDF(report, session, accentColor) {
  if (!window.jspdf) {
    await new Promise((res, rej) => {
      const s = document.createElement("script");
      s.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
      s.onload = res; s.onerror = rej;
      document.head.appendChild(s);
    });
  }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  doc.setFillColor(155, 94, 56);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text("Samvedna — Behavioural Screening Report", 14, 14);
  doc.setFontSize(9); doc.setFont("helvetica", "normal");
  doc.text("संवेदना · Empathy Through Understanding · Not a medical diagnosis", 14, 23);
  doc.setTextColor(44, 31, 14);
  doc.setFontSize(13); doc.setFont("helvetica", "bold");
  doc.text("Session Summary", 14, 46);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  const rows = [
    ["Session ID", session.sessionId || "N/A"],
    ["Date", new Date(session.startedAt || Date.now()).toLocaleDateString("en-IN", { dateStyle: "long" })],
    ["Duration", `~${Math.round((session.scoreCount || 0) * 3 / 60)} minutes`],
    ["Average Score", `${session.avgScore || 0} / 100`],
    ["Classification", `${session.lastLevel?.level || "N/A"} — ${session.lastLevel?.label || ""}`],
  ];
  rows.forEach(([l, v], i) => {
    doc.setFont("helvetica", "bold"); doc.setTextColor(138, 117, 96); doc.text(l + ":", 14, 58 + i * 10);
    doc.setFont("helvetica", "normal"); doc.setTextColor(44, 31, 14); doc.text(v, 70, 58 + i * 10);
  });
  if (report.recommendation) {
    doc.setFontSize(13); doc.setFont("helvetica", "bold"); doc.setTextColor(44, 31, 14);
    doc.text("Recommendation", 14, 120);
    doc.setFontSize(11); doc.setTextColor(155, 94, 56);
    doc.text(report.recommendation.title, 14, 130);
    doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(51, 65, 85);
    doc.text(doc.splitTextToSize(report.recommendation.text, 182), 14, 140);
  }
  doc.setFontSize(8); doc.setTextColor(138, 117, 96);
  doc.text(`Generated by Samvedna on ${new Date().toLocaleString("en-IN")}`, 14, 285);
  doc.save(`samvedna-report-${(session.sessionId || "session").slice(0, 16)}.pdf`);
}

const URGENCY_COLOR = { routine: "#22c55e", moderate: "#f59e0b", high: "#f97316", urgent: "#ef4444" };

export default function Dashboard({ sessionId: currentId, dark, theme: t }) {
  const [sessions, setSessions] = useState([]);
  const [selected, setSelected] = useState(null);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [loadingR, setLoadingR] = useState(false);
  const [error, setError] = useState(null);
  const [exporting, setExporting] = useState(false);
  const [tab, setTab] = useState("sessions");

  const accent = t?.accent || "#9b5e38";
  const bg = t?.cardBg || "#fff";
  const text = t?.text || "#2c1f0e";
  const muted = t?.muted || "#8a7560";
  const border = t?.border || "#e8ddd0";
  const tagBg = t?.tagBg || "#f5ede2";

  const lvlColor = (lvl) => ({ "Level 0": "#22c55e", "Level 1": "#f59e0b", "Level 2": "#f97316", "Level 3": "#ef4444" }[lvl] || "#9b5e38");

  useEffect(() => { fetch_sessions(); const iv = setInterval(fetch_sessions, 10000); return () => clearInterval(iv); }, []);

  const fetch_sessions = async () => {
    try {
      const r = await fetch(`${BACKEND_URL}/api/sessions`);
      const d = await r.json();
      if (d.success) setSessions(d.sessions || []);
      setError(null);
    } catch { setError("Cannot reach backend. Is Flask running?"); }
    finally { setLoading(false); }
  };

  const fetchDetail = async (sid) => {
    setLoadingR(true); setTab("detail");
    try {
      const r = await fetch(`${BACKEND_URL}/api/session/${sid}`);
      const d = await r.json();
      if (d.success) { setSelected(d.report.summary); setReport(d.report); }
    } catch { setError("Could not load session detail."); }
    finally { setLoadingR(false); }
  };

  return (
    <div style={{ background: bg, borderRadius: 24, border: `1px solid ${border}`, overflow: "hidden", boxShadow: "0 4px 24px rgba(0,0,0,0.04)" }}>
      {/* Header */}
      <div style={{ padding: "18px 22px", borderBottom: `1px solid ${border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <div style={{ fontFamily: "'Playfair Display',serif", fontSize: 18, color: accent }}>Guardian View 🌸</div>
          <div style={{ fontSize: 12, color: muted, marginTop: 2 }}>{sessions.length} session{sessions.length !== 1 ? "s" : ""} recorded</div>
        </div>
        <button onClick={fetch_sessions} style={{ padding: "7px 16px", borderRadius: 99, border: `1px solid ${border}`, background: tagBg, color: muted, fontFamily: "'Nunito',sans-serif", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
          ↻ Refresh
        </button>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", borderBottom: `1px solid ${border}`, padding: "0 22px" }}>
        {[["sessions", "All Sessions"], ["detail", "Session Detail"]].map(([k, l]) => (
          <button key={k} onClick={() => setTab(k)} style={{
            padding: "11px 18px", background: "none", border: "none", cursor: "pointer",
            fontFamily: "'Nunito',sans-serif", fontSize: 13, fontWeight: 700,
            color: tab === k ? accent : muted,
            borderBottom: `2px solid ${tab === k ? accent : "transparent"}`,
            marginBottom: -1,
          }}>{l}</button>
        ))}
      </div>

      {error && (
        <div style={{ margin: "12px 20px", padding: "10px 16px", background: "#fef2f2", borderRadius: 12, border: "1px solid #fca5a5", color: "#b91c1c", fontSize: 13 }}>{error}</div>
      )}

      {/* Sessions list */}
      {tab === "sessions" && (
        <div style={{ maxHeight: 520, overflowY: "auto", padding: 16, display: "flex", flexDirection: "column", gap: 10 }}>
          {loading && <div style={{ padding: 40, textAlign: "center", color: muted }}>Loading sessions…</div>}
          {!loading && sessions.length === 0 && (
            <div style={{ padding: "40px 20px", textAlign: "center", color: muted, fontSize: 14 }}>
              <div style={{ fontSize: 40, marginBottom: 12 }}>🌱</div>
              No sessions yet. Start a detection session to see data here.
            </div>
          )}
          {sessions.map(s => {
            const lc = lvlColor(s.lastLevel?.level);
            const isCurrent = s.sessionId === currentId;
            return (
              <div key={s.sessionId} onClick={() => fetchDetail(s.sessionId)} style={{
                padding: "14px 16px", borderRadius: 16, border: `1.5px solid ${isCurrent ? accent : border}`,
                background: isCurrent ? tagBg : bg, cursor: "pointer",
                display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12,
                transition: "transform 0.15s, box-shadow 0.15s",
              }}>
                <div style={{ display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <div style={{ width: 10, height: 10, borderRadius: "50%", background: lc, flexShrink: 0 }} />
                    <span style={{ fontSize: 12, fontWeight: 800, color: lc }}>{s.lastLevel?.level || "—"}</span>
                    {isCurrent && <span style={{ fontSize: 9, fontWeight: 800, background: "#ef4444", color: "#fff", padding: "1px 7px", borderRadius: 99 }}>LIVE</span>}
                  </div>
                  <div style={{ fontSize: 11, color: muted, fontFamily: "monospace", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {s.sessionId?.slice(0, 28)}…
                  </div>
                  <div style={{ fontSize: 11, color: muted }}>
                    {new Date(s.startedAt || Date.now()).toLocaleDateString("en-IN")} · ~{Math.round((s.scoreCount || 0) * 3 / 60)}m · {s.scoreCount || 0} pts
                  </div>
                </div>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4, flexShrink: 0 }}>
                  <Sparkline data={s.scoreHistory || []} color={lc} />
                  <div>
                    <span style={{ fontSize: 20, fontWeight: 900, color: lc }}>{s.avgScore}</span>
                    <span style={{ fontSize: 11, color: muted }}>/100</span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Session detail */}
      {tab === "detail" && (
        <div style={{ maxHeight: 560, overflowY: "auto", padding: 18, display: "flex", flexDirection: "column", gap: 16 }}>
          {loadingR && <div style={{ padding: 40, textAlign: "center", color: muted }}>Loading session data…</div>}
          {!loadingR && !report && (
            <div style={{ padding: "40px 20px", textAlign: "center", color: muted }}>
              <div style={{ fontSize: 40, marginBottom: 12 }}>🌸</div>
              Select a session from the list to see its full detail.
            </div>
          )}
          {!loadingR && report && selected && (() => {
            const rec = report.recommendation;
            const uc = URGENCY_COLOR[rec?.urgency] || accent;
            return (
              <>
                {/* Stats row */}
                <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 10 }}>
                  {[
                    { l: "Avg", v: selected.avgScore },
                    { l: "Peak", v: selected.maxScore },
                    { l: "Low", v: selected.minScore },
                    { l: "Points", v: selected.scoreCount },
                  ].map(s => (
                    <div key={s.l} style={{ background: tagBg, borderRadius: 14, padding: "14px 10px", textAlign: "center", border: `1px solid ${border}` }}>
                      <div style={{ fontSize: 22, fontWeight: 900, color: accent }}>{s.v}</div>
                      <div style={{ fontSize: 11, color: muted, marginTop: 2 }}>{s.l}</div>
                    </div>
                  ))}
                </div>

                {/* Chart */}
                <div style={{ background: tagBg, borderRadius: 16, padding: "16px 18px", border: `1px solid ${border}` }}>
                  <div style={{ fontFamily: "'Playfair Display',serif", color: accent, marginBottom: 12, fontSize: 15 }}>Score over time</div>
                  <ScoreChart scores={report.scores || (selected.scoreHistory || []).map(v => ({ asdScore: v }))} accentColor={accent} border={border} muted={muted} />
                </div>

                {/* Recommendation */}
                {rec && (
                  <div style={{ borderRadius: 16, padding: "16px 18px", background: uc + "15", border: `1.5px solid ${uc}` }}>
                    <div style={{ fontSize: 14, fontWeight: 800, color: uc, marginBottom: 6 }}>{rec.title}</div>
                    <p style={{ fontSize: 13, color: text, lineHeight: 1.6 }}>{rec.text}</p>
                  </div>
                )}

                {/* Export */}
                <button
                  onClick={async () => { setExporting(true); try { await exportPDF(report, selected, accent); } finally { setExporting(false); } }}
                  disabled={exporting}
                  style={{ padding: "13px 20px", borderRadius: 99, border: "none", background: accent, color: "#fff", fontWeight: 800, fontSize: 14, cursor: "pointer", fontFamily: "'Nunito',sans-serif", opacity: exporting ? 0.6 : 1, transition: "opacity 0.15s" }}>
                  {exporting ? "Generating…" : "🌸 Export Doctor Report (PDF)"}
                </button>
              </>
            );
          })()}
        </div>
      )}
    </div>
  );
}